### ISSUE TITLE
报警弹窗，处理人和处理信息改成必填

### ISSUE THREAD

**Issue by jsrider** [jsrider/ex-project#1]
RT，两个input 必填，若未填点提交，飘红提示不能为空，阻止提交。

图片也可以直接粘贴 上去：
![image](https://cloud.githubusercontent.com/assets/6985319/19914357/f77d685a-a0e4-11e6-86f7-a04ef6e3d500.png)

**Comment by kirito141211** [comment]
![image](https://cloud.githubusercontent.com/assets/22556913/19914707/b6e4f918-a0e7-11e6-9f5b-fac78de69fd3.png)

**Comment by jsrider** [comment]
alertDialogSubmit 返回 0 就关闭 报警弹窗了

**Comment by jsrider** [comment]
传递信息 station、monitor_point 不传为默认值，form 改变后，会传上
