### ISSUE TITLE
本地测试用链接

### ISSUE THREAD

**Issue by kirito141211** [jsrider/ex-project#17]
<a class="c-btn c-btn-primary OP_LOG_BTN" href="http://localhost:8088/api/getExcel?station=zhongxinzhan&time_range=2016%2F11%2F12%2C2016%2F11%2F12&monitor_point=all&data_info=all&time_lishi=1800&type=yue" target="_blank">立即下载</a>

**Comment by kirito141211** [comment]
'<a class="c-btn c-btn-primary OP_LOG_BTN" href="http://localhost:8088/api/getExcel?station=zhongxinzhan&time_range=2016%2F11%2F12%2C2016%2F11%2F12&monitor_point=all&data_info=all&time_lishi=1800&type=yue" target="_blank">立即下载</a>'

**Comment by kirito141211** [comment]
class="c-btn c-btn-primary OP_LOG_BTN" href="http://localhost:8088/api/getExcel?station=zhongxinzhan&time_range=2016%2F11%2F12%2C2016%2F11%2F12&monitor_point=all&data_info=all&time_lishi=1800&type=yue" target="_blank"

**Comment by jsrider** [comment]
![image](https://cloud.githubusercontent.com/assets/6985319/20264046/8b596e48-aaa4-11e6-9aba-72755cf08e75.png)
