### ISSUE TITLE
坨一 箭头与数据不对应

### ISSUE THREAD

**Issue by kirito141211** [jsrider/ex-project#22]
1坨一产气
2轻烃进口
3轻烃出口（箭头跑到坨一备用去了）
4去宁海（箭头跑到坨一外供去了）
5坨一外供（跑到轻烃出口去了）
6坨一自用（跑到镇政府去了）
7坨一备用（跑到坨一自用去了）
8镇政府（跑到去宁海去了）
![image](https://cloud.githubusercontent.com/assets/22556913/20672213/60779958-b5bb-11e6-8f42-98d4c9475388.png)
图中其他顺序没错  只是箭头错了

**Comment by jsrider** [comment]
已经改好上传
