### ISSUE TITLE
传感器详情BUG

### ISSUE THREAD

**Issue by kirito141211** [jsrider/ex-project#25]
坨一站详情顺序对不上顺序如下
![image](https://cloud.githubusercontent.com/assets/22556913/21338006/3fdbe534-c6ad-11e6-9c99-fcafb2b6d15b.png)

**Comment by kirito141211** [comment]
检测点数据来源能从index.php来吗  
之前检测点名称有改动过
如下  坨一站：“坨一汇东”改为“坨一备用”
         坨四站：“去总外输”改为“坨四外输”

**Comment by jsrider** [comment]
done
